---
- collection: &Backend.Core.ProductionSpeed
    items:
        - key: production_speed_extremely_slow
          name: "Extremely Slow"
          multiplier: 0.25
        - key: production_speed_super_slow
          name: "Super Slow"
          multiplier: 0.35
        - key: production_speed_very_slow
          name: FE_PRODUCTION_SPEED_VERY_SLOW
          multiplier: 0.5
        - key: production_speed_slow
          name: FE_PRODUCTION_SPEED_SLOW
          multiplier: 0.75
        - key: production_speed_normal
          name: FE_PRODUCTION_SPEED_NORMAL
          multiplier: 1.0
          isDefault: true
        - key: production_speed_fast
          name: FE_PRODUCTION_SPEED_FAST
          multiplier: 1.25
        - key: production_speed_very_fast
          name: FE_PRODUCTION_SPEED_VERY_FAST
          multiplier: 1.5
...