---
- collection: &Backend.Civilizations.AntaranSettings
    items:
          - key: antaran_default_settings
            ANTARAN_DESIRED_VICTORY_CHANCES: 50
            ANTARAN_DESIRED_VICTORY_CHANCES_TOLERANCE: 5
            
            ANTARAN_ATTACK_SPAWN_PORTAL_MIN_DISTANCE: 2
            ANTARAN_ATTACK_SPAWN_PORTAL_MAX_DISTANCE: 4
            
            ANTARANS_TURNS_TO_FIRST_MIN: 70
            ANTARANS_TURNS_TO_FIRST_MAX: 90
            ANTARANS_TURNS_TO_NEXT_MIN: 25
            ANTARANS_TURNS_TO_NEXT_MAX: 45
            
            ANTARAN_FRIGATE_SHIP_BLUEPRINT_TEMPLATE: design_frigate_antaran
            ANTARAN_DESTROYER_SHIP_BLUEPRINT_TEMPLATE: design_destroyer_antaran
            ANTARAN_CRUISER_SHIP_BLUEPRINT_TEMPLATE: design_cruiser_antaran
            ANTARAN_BATTLESHIP_SHIP_BLUEPRINT_TEMPLATE: design_battleship_antaran
            ANTARAN_TITAN_SHIP_BLUEPRINT_TEMPLATE: design_titan_antaran
            ANTARAN_DOOMSTAR_SHIP_BLUEPRINT_TEMPLATE: design_doomstar_antaran
            
            ANTARAN_ATTACK_MIN_FRIGATES: 2
            ANTARAN_ATTACK_MIN_DESTROYERS: 2
            ANTARAN_ATTACK_MIN_BATTLESHIPS: 0
            ANTARAN_ATTACK_MIN_CRUISERS: 0
            ANTARAN_ATTACK_MIN_TITANS: 0
            ANTARAN_ATTACK_MIN_DOOMSTARS: 0

            ANTARAN_FRIGATE_CHANCES: 25
            ANTARAN_DESTROYER_CHANCES: 25
            ANTARAN_CRUISER_CHANCES: 20
            ANTARAN_BATTLESHIP_CHANCES: 15
            ANTARAN_TITAN_CHANCES: 10
            ANTARAN_DOOMSTAR_CHANCES: 5

            ANTARAN_ATTACK_MAX_FRIGATES: 24
            ANTARAN_ATTACK_MAX_DESTROYERS: 24
            ANTARAN_ATTACK_MAX_BATTLESHIPS: 12
            ANTARAN_ATTACK_MAX_CRUISERS: 12
            ANTARAN_ATTACK_MAX_TITANS: -1
            ANTARAN_ATTACK_MAX_DOOMSTARS: -1
            
            ANTARAN_DEFENSE_MIN_FRIGATES: 15
            ANTARAN_DEFENSE_MIN_DESTROYERS: 15
            ANTARAN_DEFENSE_MIN_BATTLESHIPS: 10
            ANTARAN_DEFENSE_MIN_CRUISERS: 8
            ANTARAN_DEFENSE_MIN_TITANS: 6
            ANTARAN_DEFENSE_MIN_DOOMSTARS: 1
           
            ANTARAN_SHIP_MODULE_DRIVE_KEY: shipmodule_antaran_drive
            ANTARAN_SHIP_MODULE_BIOLOGICAL_BOMB_KEY: shipmodule_antaran_biological_bombs
            ANTARAN_SHIP_MODULE_MISSILE_KEY: shipmodule_antaran_nuclear_missile
            ANTARAN_SHIP_MODULE_TORPEDOE_KEY: shipmodule_antaran_proton_torpedoes
            ANTARAN_SHIP_MODULE_BEAM_KEY: shipmodule_antaran_fusion_beam 
            
          - key: antaran_test_settings
            ANTARAN_DESIRED_VICTORY_CHANCES: 50
            ANTARAN_DESIRED_VICTORY_CHANCES_TOLERANCE: 5
            
            ANTARAN_ATTACK_SPAWN_PORTAL_MIN_DISTANCE: 2
            ANTARAN_ATTACK_SPAWN_PORTAL_MAX_DISTANCE: 4
            
            ANTARANS_TURNS_TO_FIRST_MIN: 1
            ANTARANS_TURNS_TO_FIRST_MAX: 2
            ANTARANS_TURNS_TO_NEXT_MIN: 1
            ANTARANS_TURNS_TO_NEXT_MAX: 2
            
            ANTARAN_FRIGATE_SHIP_BLUEPRINT_TEMPLATE: design_frigate_antaran
            ANTARAN_DESTROYER_SHIP_BLUEPRINT_TEMPLATE: design_destroyer_antaran
            ANTARAN_CRUISER_SHIP_BLUEPRINT_TEMPLATE: design_cruiser_antaran
            ANTARAN_BATTLESHIP_SHIP_BLUEPRINT_TEMPLATE: design_battleship_antaran
            ANTARAN_TITAN_SHIP_BLUEPRINT_TEMPLATE: design_titan_antaran
            ANTARAN_DOOMSTAR_SHIP_BLUEPRINT_TEMPLATE: design_doomstar_antaran
            
            ANTARAN_ATTACK_MIN_FRIGATES: 2
            ANTARAN_ATTACK_MIN_DESTROYERS: 2
            ANTARAN_ATTACK_MIN_BATTLESHIPS: 0
            ANTARAN_ATTACK_MIN_CRUISERS: 0
            ANTARAN_ATTACK_MIN_TITANS: 0
            ANTARAN_ATTACK_MIN_DOOMSTARS: 0

            ANTARAN_FRIGATE_CHANCES: 25
            ANTARAN_DESTROYER_CHANCES: 25
            ANTARAN_CRUISER_CHANCES: 20
            ANTARAN_BATTLESHIP_CHANCES: 15
            ANTARAN_TITAN_CHANCES: 10
            ANTARAN_DOOMSTAR_CHANCES: 5

            ANTARAN_ATTACK_MAX_FRIGATES: 24
            ANTARAN_ATTACK_MAX_DESTROYERS: 24
            ANTARAN_ATTACK_MAX_BATTLESHIPS: 12
            ANTARAN_ATTACK_MAX_CRUISERS: 12
            ANTARAN_ATTACK_MAX_TITANS: -1
            ANTARAN_ATTACK_MAX_DOOMSTARS: -1
            
            ANTARAN_DEFENSE_MIN_FRIGATES: 16
            ANTARAN_DEFENSE_MIN_DESTROYERS: 16
            ANTARAN_DEFENSE_MIN_BATTLESHIPS: 8
            ANTARAN_DEFENSE_MIN_CRUISERS: 8
            ANTARAN_DEFENSE_MIN_TITANS: 4
            ANTARAN_DEFENSE_MIN_DOOMSTARS: 2
           
            ANTARAN_SHIP_MODULE_DRIVE_KEY: shipmodule_antaran_drive
            ANTARAN_SHIP_MODULE_BIOLOGICAL_BOMB_KEY: shipmodule_antaran_biological_bombs
            ANTARAN_SHIP_MODULE_MISSILE_KEY: shipmodule_antaran_nuclear_missile
            ANTARAN_SHIP_MODULE_TORPEDOE_KEY: shipmodule_antaran_proton_torpedoes
            ANTARAN_SHIP_MODULE_BEAM_KEY: shipmodule_antaran_fusion_beam 
...