---
- collection: &Backend.Tactical.TacticalHazardsConfigs
    items:
        - key: hazardConfigAsteroidsNone
          smallCount: 0
          mediumCount: 0
          bigCount: 0
        - key: hazardConfigAsteroidsLow
          smallCount: 8
          mediumCount: 6
          bigCount: 3
        - key: hazardConfigAsteroidsMild
          smallCount: 14
          mediumCount: 10
          bigCount: 5
        - key: hazardConfigAsteroidsHigh
          smallCount: 18
          mediumCount: 16
          bigCount: 10
        - key: hazardConfigAsteroidsExtreme
          smallCount: 24
          mediumCount: 25
          bigCount: 16
        - key: hazardConfigNebulaeNone
          nebulaeCount: 0
        - key: hazardConfigNebulaeLow
          nebulaeCount: 2
        - key: hazardConfigNebulaeMild
          nebulaeCount: 4
        - key: hazardConfigNebulaeHigh
          nebulaeCount: 6
        - key: hazardConfigNebulaeExtreme
          nebulaeCount: 8
...